---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"

  # Daily: Check minor and patch updates
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase
