---
name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 🔨 Build Packages
        run: npm run build
